#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Values worth keeping land here rather than in a real .env: this is a release
# record, not application configuration.
ENV_FILE="${ENV_FILE:-$HOME/tribios-copr-release.env}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VERSION="$(sed -n 's/^project(tribios_vfs VERSION \([0-9.]*\).*/\1/p' CMakeLists.txt)"
TAG="v$VERSION"
ARCHIVE="tribios-vfs-$VERSION.tar.gz"
GITHUB_SLUG="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo JediNakDev/tribios-vfs)"
CLONE_URL="https://github.com/$GITHUB_SLUG.git"
COPR_PROJECT="tribios-vfs"

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

# Copr is driven by copr-cli, which is a Fedora tool. On a machine without it,
# the same calls run inside a small container image built once from the token
# already sitting in ~/.config/copr.
COPR_IMAGE="tribios-copr-cli"
CONTAINER=""
copr_cli() {
  if command -v copr-cli >/dev/null 2>&1; then
    copr-cli "$@"
  else
    "$CONTAINER" run --rm -v "$HOME/.config/copr:/root/.config/copr:ro" "$COPR_IMAGE" copr-cli "$@"
  fi
}

banner "Tribios VFS $TAG: Fedora and EPEL preview through Copr"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools and the tree this procedure needs."

command -v git >/dev/null || die "git is not installed"
command -v gh  >/dev/null || die "the GitHub CLI (gh) is not installed"
gh auth status >/dev/null 2>&1 || die "gh is not logged in; run: gh auth login"

if   command -v podman >/dev/null 2>&1; then CONTAINER=podman
elif command -v docker >/dev/null 2>&1; then CONTAINER=docker
else die "neither podman nor docker is installed; the acceptance runs need one"
fi
"$CONTAINER" info >/dev/null 2>&1 || die "$CONTAINER is installed but not running"

say "version $VERSION, tag $TAG, repository $GITHUB_SLUG"
say "container runtime: $CONTAINER"
note "the acceptance containers run on $(uname -m), so that is the architecture they prove"

[[ -z "$(git status --porcelain)" ]] || die "the working tree is dirty; commit or clean it first"
git fetch --quiet origin
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
say "on branch $BRANCH at $(git rev-parse --short HEAD)"
step "The packaging work must be merged before tagging, so this should be the default branch, up to date with origin."
confirm "Is this the commit you want to release as $TAG?" || die "stopping; check out the commit you want to release"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Copr API token"
say "copr-cli authenticates with a token file at ~/.config/copr."

if [[ -f "$HOME/.config/copr" ]]; then
  say "a token file already exists."
  note "tokens expire; if a later stage reports an authentication error, come back and replace it"
else
  open_url "https://copr.fedorainfracloud.org/api/"
  step "Log in with your Fedora account."
  step "The page shows a block starting with [copr-cli]. Copy the whole block."
  step "Paste it into ~/.config/copr, which this wizard will open for you to fill."
  mkdir -p "$HOME/.config"
  pause "Press Enter to open an editor for ~/.config/copr"
  "${EDITOR:-vi}" "$HOME/.config/copr"
  [[ -s "$HOME/.config/copr" ]] || die "$HOME/.config/copr is empty; re-run once you have pasted the token"
  chmod 600 "$HOME/.config/copr"
fi

COPR_OWNER="$(sed -n 's/^username[[:space:]]*=[[:space:]]*//p' "$HOME/.config/copr" | head -1)"
[[ -n "$COPR_OWNER" ]] || die "no username in ~/.config/copr; the pasted block is incomplete"
say "Copr owner: $COPR_OWNER"

if ! command -v copr-cli >/dev/null 2>&1; then
  say "copr-cli is not installed here, so it will run from a small container image."
  "$CONTAINER" image inspect "$COPR_IMAGE" >/dev/null 2>&1 ||
    printf 'FROM fedora:latest\nRUN dnf -y install copr-cli && dnf clean all\n' |
      "$CONTAINER" build -t "$COPR_IMAGE" - || die "could not build the copr-cli helper image"
fi
copr_cli whoami >/dev/null || die "copr-cli could not authenticate; check the token in ~/.config/copr"

COPR_SLUG="$COPR_OWNER/$COPR_PROJECT"
COPR_PROJECT_URL="https://copr.fedorainfracloud.org/coprs/$COPR_OWNER/$COPR_PROJECT/"
write_env COPR_OWNER "$COPR_OWNER"
write_env COPR_SLUG "$COPR_SLUG"
write_env COPR_PROJECT_URL "$COPR_PROJECT_URL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Publish the $TAG release"
say "The spec fetches the release archive, so nothing can build until the tag exists."
warn "A published tag is never re-cut, moved or overwritten: downstream recipes pin its checksum."

if gh release view "$TAG" >/dev/null 2>&1; then
  say "$TAG is already released; leaving it alone."
else
  confirm "Create and push the tag $TAG now?" || die "stopping before the irreversible step"
  git tag -a "$TAG" -m "$TAG"
  git push origin "$TAG"
  say "pushed $TAG; the release workflow builds the archive and its checksum."
  open_url "https://github.com/$GITHUB_SLUG/actions/workflows/release.yml"
  until gh release view "$TAG" >/dev/null 2>&1; do
    printf '  %s… waiting for the release workflow%s\r' "$DIM" "$RESET"
    sleep 15
  done
  printf '\n'
fi
say "release published: https://github.com/$GITHUB_SLUG/releases/tag/$TAG"
write_env RELEASE_TAG "$TAG"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Record the archive checksum"
say "Every downstream recipe pins this checksum, so it belongs in the release record."

TMPDIR_DL="$(mktemp -d)"
gh release download "$TAG" --repo "$GITHUB_SLUG" --pattern "$ARCHIVE*" --dir "$TMPDIR_DL" ||
  die "could not download the release assets"
RELEASE_SHA256="$(awk '{print $1}' "$TMPDIR_DL/$ARCHIVE.sha256")"
COMPUTED="$( (shasum -a 256 "$TMPDIR_DL/$ARCHIVE" 2>/dev/null || sha256sum "$TMPDIR_DL/$ARCHIVE") | awk '{print $1}')"
[[ "$RELEASE_SHA256" == "$COMPUTED" ]] ||
  die "the published checksum does not match the published archive; do not build from it"
rm -rf "$TMPDIR_DL"
say "archive and checksum agree."
write_env RELEASE_ARCHIVE_URL "https://github.com/$GITHUB_SLUG/releases/download/$TAG/$ARCHIVE"
write_env RELEASE_SHA256 "$RELEASE_SHA256"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the Copr project and its chroots"
say "Claim only chroots that actually build: the two current stable Fedora releases,"
say "rawhide, and epel-10, on x86_64 and aarch64."

ALL_CHROOTS="$(copr_cli list-chroots 2>/dev/null)" || die "could not list Copr chroots"
FEDORA_STABLE="$(printf '%s\n' "$ALL_CHROOTS" | sed -n 's/^fedora-\([0-9]*\)-x86_64.*/\1/p' | sort -rn | head -2)"
CHROOTS=()
for release in $FEDORA_STABLE rawhide; do
  CHROOTS+=("fedora-$release-x86_64" "fedora-$release-aarch64")
done
CHROOTS+=("epel-10-x86_64" "epel-10-aarch64")

say "chroots: ${CHROOTS[*]}"
note "epel-9 is deliberately left out: RHEL 9's system GCC has no <expected>, so it needs"
note "gcc-toolset-14 and CMake 3.24, and the spec's conditional for it is untested. Stage 9 offers it."

CHROOT_ARGS=()
for chroot in "${CHROOTS[@]}"; do CHROOT_ARGS+=(--chroot "$chroot"); done

if copr_cli get "$COPR_SLUG" >/dev/null 2>&1; then
  say "the project already exists; making sure the chroots are enabled."
  copr_cli modify "${CHROOT_ARGS[@]}" "$COPR_SLUG" ||
    warn "could not update the chroots; check them at $COPR_PROJECT_URL"
else
  confirm "Create the Copr project $COPR_SLUG?" || die "stopping"
  copr_cli create "${CHROOT_ARGS[@]}" \
    --description "Preview RPMs for Tribios VFS, copy-on-write Workspaces for Git projects." \
    --instructions "Preview quality. See https://github.com/$GITHUB_SLUG/blob/main/docs/packaging/copr.md" \
    "$COPR_PROJECT" || die "could not create the Copr project"
fi
say "project: $COPR_PROJECT_URL"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Point the package at the tag"
say "The package uses the SCM source type with the make srpm method, so Copr clones"
say "this repository at the tag and runs .copr/Makefile to produce the source RPM."

PACKAGE_ARGS=(--name tribios-vfs --clone-url "$CLONE_URL" --commit "$TAG"
              --spec packaging/rpm/tribios-vfs.spec --type git --method make_srpm)
if copr_cli get-package --name tribios-vfs "$COPR_SLUG" >/dev/null 2>&1; then
  copr_cli edit-package-scm "${PACKAGE_ARGS[@]}" "$COPR_SLUG" || die "could not update the package"
  say "package updated to build from $TAG."
else
  copr_cli add-package-scm "${PACKAGE_ARGS[@]}" "$COPR_SLUG" || die "could not add the package"
  say "package added, building from $TAG."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Build"
say "Building tribios-vfs in every enabled chroot. This takes a while."

BUILD_LOG="$(mktemp)"
copr_cli build-package --name tribios-vfs "$COPR_SLUG" 2>&1 | tee "$BUILD_LOG" || {
  warn "the build failed; the log above says which chroot and why"
  note "per-chroot logs: $COPR_PROJECT_URL"
  die "fix the spec or drop the failing chroot, then re-run this wizard"
}
COPR_BUILD_ID="$(sed -n 's/.*[Bb]uild[s]* \([0-9][0-9]*\).*/\1/p' "$BUILD_LOG" | head -1)"
rm -f "$BUILD_LOG"
say "every chroot built."
[[ -n "$COPR_BUILD_ID" ]] && write_env COPR_BUILD_ID "$COPR_BUILD_ID"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Acceptance: clean install and the core workflow"
say "A build that succeeds is not a package that works. This installs from the"
say "published repository in a clean container and runs the core workflow."

ARCH="$(uname -m)"
# shellcheck disable=SC2016  # expanded inside the container, not here
SMOKE='
set -euxo pipefail
dnf -y install dnf-plugins-core
dnf -y copr enable "$COPR_SLUG" "$CHROOT"
dnf -y install tribios-vfs
rpm -q tribios-vfs
test "$(tribios version)" = "tribios $VERSION"
rpm -ql tribios-vfs
git config --global user.email packaging@example.com
git config --global user.name Packaging
git init -q /tmp/project
cd /tmp/project
git commit -q --allow-empty -m init
tribios configure /tmp/project
tribios daemon start
tribios workspace create smoke
tribios workspace list | grep -q smoke
# The mounted path is the real seam; tribios fs is the same engine and is the
# honest fallback when the container cannot get /dev/fuse.
if echo -n hello > /tmp/project/.tribios/mnt/smoke/kept.txt 2>/dev/null; then
  test "$(cat /tmp/project/.tribios/mnt/smoke/kept.txt)" = hello
else
  echo "WARNING: no mount in this container, exercising the engine directly"
  tribios fs write smoke kept.txt hello 0
  test "$(tribios fs read smoke kept.txt)" = hello
fi
tribios daemon stop
# Erasing the package must not touch project data.
dnf -y remove tribios-vfs
test -f /tmp/project/.tribios/meta.db
test ! -e /usr/bin/tribios
echo ACCEPTANCE-OK
'

# Plain strings, not arrays: macOS still ships bash 3.2, where an empty array
# expansion under set -u is an error.
PASSED_LIST=""; FAILED_LIST=""
for chroot in "${CHROOTS[@]}"; do
  [[ "$chroot" == *"-$ARCH" ]] || { note "skipping $chroot: this machine is $ARCH"; continue; }
  case "$chroot" in
    fedora-rawhide-*) image="fedora:rawhide" ;;
    fedora-*)         image="fedora:${chroot#fedora-}"; image="${image%-*}" ;;
    epel-10-*)        image="quay.io/centos/centos:stream10" ;;
    *)                image="" ;;
  esac
  [[ -n "$image" ]] || { note "no container image known for $chroot; test it by hand"; continue; }

  say "── $chroot via $image"
  # /dev/fuse has to exist in the container host. Where it does not, the run
  # still happens without it and the smoke says so rather than reporting a
  # false failure of the package.
  RUN_ARGS=(--rm --device /dev/fuse --cap-add SYS_ADMIN)
  if ! "$CONTAINER" run "${RUN_ARGS[@]}" "$image" true >/dev/null 2>&1; then
    warn "$CONTAINER cannot pass /dev/fuse here, so this run cannot prove mounting"
    RUN_ARGS=(--rm)
  fi
  if "$CONTAINER" run "${RUN_ARGS[@]}" \
       -e COPR_SLUG="$COPR_SLUG" -e CHROOT="$chroot" -e VERSION="$VERSION" \
       "$image" bash -c "$SMOKE"; then
    PASSED_LIST="$PASSED_LIST $chroot"; say "$chroot passed"
  else
    FAILED_LIST="$FAILED_LIST $chroot"; warn "$chroot failed"
  fi
  pause "Press Enter for the next chroot"
done

[[ -z "$FAILED_LIST" ]] || SKIPPED+=("failing chroots, either fix them or disable them:$FAILED_LIST")
write_env ACCEPTED_CHROOTS "${PASSED_LIST# }"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "The two checks that need a second release"
say "Two acceptance criteria cannot be met by a first release, so they are due"
say "the next time you run this wizard:"
step "Upgrade preserves project data: install the previous preview, create a Workspace"
say "  with a file in it, dnf upgrade tribios-vfs, then confirm the file is still there."
step "epel-9: enable the chroot, build, and keep it only if it passes on its own."
say "  copr-cli modify --chroot epel-9-x86_64 --chroot epel-9-aarch64 $COPR_SLUG"
SKIPPED+=("upgrade-preserves-data, once a second preview version exists")
SKIPPED+=("epel-9, if you want it: enable the chroot, rebuild, keep it only if it passes")
pause "Press Enter for the summary"

finish

printf '%s%s  Worth keeping%s\n\n' "$BOLD" "$BLUE" "$RESET"
note "saved to $ENV_FILE"
printf '  %-22s %s\n' "Copr project"   "$COPR_PROJECT_URL"
printf '  %-22s %s\n' "Copr repo slug" "$COPR_SLUG"
printf '  %-22s %s\n' "Build ID"       "${COPR_BUILD_ID:-unknown}"
printf '  %-22s %s\n' "Release tag"    "$TAG"
printf '  %-22s %s\n' "Archive sha256" "$RELEASE_SHA256"
printf '  %-22s %s\n' "Chroots passed" "${PASSED_LIST:-  none}"
printf '\n  %sInstall instructions to publish%s\n' "$BOLD" "$RESET"
printf '    sudo dnf copr enable %s\n' "$COPR_SLUG"
printf '    sudo dnf install tribios-vfs\n\n'
note "if the Copr owner is not the slug docs/packaging/copr.md prints, correct the doc"
printf '\n'
